# Generated by Django 5.0.6 on 2026-07-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_contact', models.CharField(help_text="Team leader's email or phone number.", max_length=150)),
                ('spin_count', models.IntegerField(default=0)),
                ('api_1', models.CharField(blank=True, max_length=100, null=True)),
                ('api_2', models.CharField(blank=True, max_length=100, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Profile',
                'verbose_name_plural': 'Team Profiles',
            },
        ),
    ]
